### ISSUE TITLE
DailyScrapValue config value not implemented

### ISSUE THREAD

**Issue by Shaosil** [Kraykennn/LC-DynamicDeadline#2]
The line `timeUntilDeadline = Mathf.Clamp(Mathf.Ceil(profitQuota / 200), 4f, 10f);` in TestMod/Patches/ProfitQuotaPatch.cs doesn't appear to support the DailyScrapValue config setting and always uses 200.

Also, just a suggestion, but it may be nice to have the clamped values 4 and 10 days could also be configurable (perhaps with a min/max of like 2 and 20 or something).

**Comment by Kraykennn** [comment]
Hi there, currently I'm having an issue with updating the master branch, so the code displayed on GitHub is not accurate. I'll be manually adding/removing files until I resolve this issue starting with the next update. (Soon)
