### ISSUE TITLE
The Sell% can go negative

### ISSUE THREAD

**Issue by BeeDoodl** [Kraykennn/LC-DynamicDeadline#3]
If your days go beyond a certain amount, the sell% for The Company will go negative (For example, on 8/9 days left it was at -87%). This negative sell percentage is used in calculation. This results in losing credits for selling scrap, and the quota being artificially higher (since it adds -(X) to the amount counting towards quota.

**Comment by Kraykennn** [comment]
This shouldn't be an issue if you go through until your deadline. Dynamic Deadline was designed to remove the eventual impossibility from the game, not make it exceptionally easier. 
I even attached a message into the DailyScrapValue config to express that intention "Challenge yourself, nerd". 

If all you're looking for is to have an infinite number of days while being able to collect scrap stress free and NEVER fail, I'd recommend looking at the GameMaster mod or any other Host Tools mod.
