### ISSUE TITLE
Can't get it to work

### ISSUE THREAD

**Issue by Mofker** [Kraykennn/LC-DynamicDeadline#4]
I've set up the mod and changed the DailyScrapValue to 500 from 200 to test and the increas will still be 200.
Days are not increasing when the quota goes over 600 either.

**Comment by Kraykennn** [comment]
I don't quite understand the issue you're having. Are you modifying the DailyScrapValue to 500 while having the game open? Currently, the mod does not update the config while the game is already loaded. 

If you set the value to 500 and then started your game, you wouldn't get an extra day until your quota reaches 1501-2000, two extra days at 2001-2500 and so forth. This part is confirmed to be working through my own personal use and messages from members of the lethal company modding discord. 

If this isn't the issue you're having, please elaborate and I'll do my best to accommodate.
