### ISSUE TITLE
[Sugestion] An option to increase the daily scrap value based on how many quotas completed

### ISSUE THREAD

**Issue by theRealCarneiro** [Kraykennn/LC-DynamicDeadline#5]
## Why
This game depends too much on rng some times, and basing the daily scrap on how much you get in a specific round will start making you think about holding back items so the quota doesn't get too high.

## Possible fix
So I sugest adding an option to start the daily scrap at an SCRAP_MIN value (lets say 200), then after each quoata is complete, increase it by a fixed QUOTA_DAILY_INCREASE amount (lets say 30). 

## Consequences
The game still gets harder after each quota but you don't have to think about holding items back

An example using 200 as the daily scrap to start, and increasing it by 30 on each quota
| Quota | Daily | Days |
|-------|-------|------|
| 200   | 200   | 3    |
| 500   | 230   | 3    |
| 800   | 260   | 4    |
| 1100  | 290   | 4    |
| 1400  | 320   | 5    |
| 1700  | 350   | 5    |
| 2000  | 380   | 6    |

## Keep it as an option
Keep the default mod behaviour, but add this as an option

**Comment by Kraykennn** [comment]
See #6
